spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passwords
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12Eren89


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  security:
    user:
      name: "eren"
      password: "12Eren89"

  main:
    banner-mode: off

logging:
  level:
    root: warn